apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-app
  namespace: argocd               # Application CR thường nằm ở namespace argocd
spec:
  project: default                # hoặc project bạn đang dùng
  source:
    repoURL: https://github.com/DaoAnhThien/kltn1.git
    targetRevision: main          # hoặc branch/tag của bạn
    path: kube  # thư mục chứa deployment.yml + service.yml
  destination:
    server: https://kubernetes.default.svc   # cluster mặc định (in-cluster)
    namespace: netflix-app                   # ← THÊM DÒNG NÀY, namespace bạn muốn deploy vào
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true                   # Tự tạo namespace nếu chưa tồn tại (rất nên có)